python/front/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user/<int:pk>/', views.UserPage.as_view(), name='user'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email_login/', views.EmailLogin.as_view(), name='email_login'),
    path('email_login/complete/<token>/', views.EmailLoginComplete.as_view(), name='email_login_complete'),
]

python/front/twelS/urls.py
# -*- coding: utf-8 -*-
"""twelS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # superuserを作っていないが，一応adminのpathを推測できないものにする
    path('4KkEH5XsLQRC/', admin.site.urls),
    path('', include('search.urls')),
    path('login/', include('login.urls')), # login

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # this line is executed when DEBUG is set to True.
]

python/front/login/views.py
import datetime

from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.http import urlsafe_base64_decode
from django.views import generic

from .forms import (
    LoginForm, CustomUserCreateForm, CustomPasswordChangeForm,
    MyPasswordResetForm, CustomSetPasswordForm, EmailLoginForm
)
from .models import EmailUser, IPAddress, PasswordResetRequest, UserCreateRequest, EmailLoginRequest
import logging

logger = logging.getLogger('django')


User = get_user_model()
Emailuser = EmailUser


def get_ip(request):
    forwarded_addresses = request.META.get('HTTP_X_FORWARDED_FOR')
    if forwarded_addresses:
        # 'HTTP_X_FORWARDED_FOR'ヘッダがある場合: 転送経路の先頭要素を取得する。
        current_ip = forwarded_addresses.split(',')[0]
        logger.info('get IP from HTTP_X_FORWARDED_FOR')
    else:
        # 'HTTP_X_FORWARDED_FOR'ヘッダがない場合: 直接接続なので'REMOTE_ADDR'ヘッダを参照する。
        current_ip = request.META.get('REMOTE_ADDR')
        logger.info('get IP from REMOTE_ADDR')
    return current_ip


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'htmls/login.html'

    redirect_authenticated_user = True  # ログインしているユーザーがアクセスしたとき数式検索ページにリダイレクト

    def form_valid(self, form):
        """ログイン時にIPアドレスを取得し,未知のIPアドレスだった場合は警告メールを送信する."""
        login(self.request, form.get_user())

        try:
            user = User.objects.get(pk=self.request.user.pk)

            current_ip = get_ip(self.request)

            ip = IPAddress.objects.filter(user=user, ip_address=current_ip)

            if ip:  # 既知のIPアドレスの場合は最後にアクセスした日時を更新する
                ip_address = IPAddress.objects.get(user=user, ip_address=current_ip)
                ip_address.last_access = timezone.now()
                ip_address.save()

            else:  # 未知のIPアドレスの場合はIPアドレスを登録し,ユーザーに警告メールを送信する
                IPAddress.objects.create(user=user, ip_address=current_ip)

                origin: str = self.request.headers["Origin"]
                context = {
                    'origin': origin,
                    'user': user,
                    'ip': current_ip
                }

                subject = render_to_string('mail_template/unknown_ip/subject.txt', context)
                message = render_to_string('mail_template/unknown_ip/message.txt', context)

                user.send_mail(subject, message)

        except ObjectDoesNotExist:
            # userが存在しない場合でも正常に動作するように用意している
            pass
        except Exception as e:
            logger.error(f'{e} in login  user:{user}')

        return HttpResponseRedirect(self.get_success_url())


class Logout(generic.View):
    """ログアウトした後、ログインページにリダイレクトする。"""
    def get(self, request):
        """メール認証ログインユーザーはログアウト時にis_active=False"""
        try:
            emailuser: EmailUser = Emailuser.objects.get(email=request.user)

        except Emailuser.DoesNotExist:
            pass
        else:
            emailuser.logout(request)
        logout(request)  # パスワードを用いるUserのログアウト
        return redirect('login:login')


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'htmls/user_create.html'
    form_class = CustomUserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        origin: str = self.request.headers["Origin"]
        context = {
            'origin': origin,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('mail_template/user_create/subject.txt', context)
        message = render_to_string('mail_template/user_create/message.txt', context)

        user.send_mail(subject, message)
        return render(request=self.request, template_name='htmls/email_sent.html', context={'user': user})


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired as e:
            logger.error(f'{e} in UserCreateComplete.', stack_info=True)
            context = {
                'message': 'この認証URLは期限切れです。',
            }
            return render(request, 'htmls/token_error.html', context, status=401)

        # tokenが間違っている
        except BadSignature as e:
            logger.error(f'{e} in UserCreateComplete.', stack_info=True)
            context = {
                'message': 'この認証URLは正しくありません。',
            }
            return render(request, 'htmls/token_error.html', context, status=401)

        # それ以外のエラー
        except Exception as e:
            logger.error(f'{e} in UserCreateComplete.', stack_info=True)
            context = {
                'message': '予期していないエラーが発生しました。',
            }
            return render(request, 'htmls/token_error.html', status=401)

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
                UserCreateRequest.objects.filter(email=user.email).delete()  # リクエストを削除する．

                current_ip = get_ip(self.request)

                ip_set: QuerySet = IPAddress.objects.filter(user=user, ip_address=current_ip)

                if not ip_set:
                    # 未知のIPアドレスの場合はIPアドレスを登録する
                    IPAddress.objects.create(user=user, ip_address=current_ip)

                else:
                    # 既知のIPアドレスの場合は最後にアクセスした日時を更新する
                    ip_address = ip_set[0]
                    ip_address.last_access = timezone.now()
                    ip_address.save()

            except Exception as e:
                logger.error(f'{e} in UserCreateComplete.', stack_info=True)
                context = {
                    'message': '予期していないエラーが発生しました。',
                }
                return render(request, 'htmls/token_error.html', context, status=401)
            else:
                # 同じ認証URLに複数回アクセスした場合もindexにリダイレクト
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('search:index')


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserPage(OnlyYouMixin, generic.TemplateView):
    model = User
    template_name = 'htmls/user.html'


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('login:password_change_done')
    template_name = 'htmls/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'htmls/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'mail_template/password_reset/subject.txt'
    email_template_name = 'mail_template/password_reset/message.txt'
    template_name = 'htmls/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('login:password_reset_done')

    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "token_generator": self.token_generator,
            "from_email": self.from_email,
            "email_template_name": self.email_template_name,
            "subject_template_name": self.subject_template_name,
            "request": self.request,
            "html_email_template_name": self.html_email_template_name,
            "extra_email_context": self.extra_email_context,
        }
        form.save(**opts)
        user = form.cleaned_data['email']
        return render(request=self.request, template_name='htmls/email_sent.html', context={'user': user})


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'htmls/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('login:password_reset_complete')
    template_name = 'htmls/password_reset_confirm.html'

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
            user.save()

            # パスワードリセットのリクエストの回数制限をリセット
            user_request = PasswordResetRequest.objects.get(email=user.email)

            user_request.email_request_times = 0
            user_request.first_request_date = datetime.datetime.now()
            user_request.save()

        except (
            TypeError,
            ValueError,
            OverflowError,
            User.DoesNotExist,
            ValidationError,

python/front/login/templates/htmls/email_login.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>メールでのログイン</title>
<link href="{% static 'login/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}

        <form action="" method="POST">
            <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            </div>
            <button>ログイン</button>
        </form>

{% endblock body %}

python/front/login/templates/htmls/email_sent.html
{% extends "search/base.html" %}

{% block head %}
<title>メールを送信しました</title>
{% endblock head %}

{% block body %}
<p>
    {{ user }}にメールを送信しました。<br>
    URLからログインしてください。<br>
</p>
{% endblock body %}

python/front/login/templates/htmls/login.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>ログイン</title>
<link href="{% static 'login/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}

<br>
<h1>ログイン</h1>
<br>

<div class="cardGroup">
    <!-- 左側、ログインエリア -->
    <div class="card">
            <form action="{% url 'login:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <!-- An element to toggle between password visibility -->
                <input type="checkbox" onclick="mask_password()">Show Password
                <div><button class="button-wide">ログイン</button></div>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </form>
    </div>

    <!-- 右側、会員登録エリア -->
    <div class="card">
        <!-- buttonをinline-blockからblockに変更するためにdivを付与。 -->
        <!-- buttonを縦に並べたい。 -->
        <div><button class="button-wide">
            <a href="{% url 'login:user_create' %}" >会員登録</a>
        </button></div>
        <div><button class="button-wide">
            <a href="{% url 'login:password_reset' %}" >パスワードを忘れた方</a>
        </button></div>
        <div><button class="button-wide">
            <a href="{% url 'login:email_login' %}" >メールアドレスでのログイン</a>
        </button></div>
    </div>
</div>

<p>
    <br>
    パスワードなしでログインしたい場合には「メールアドレスでのログイン」を行なってください。<br>
    この場合、ログインの度に認証メールにあるURLをクリック/タップする必要があります。<br><br>

    パスワードありでログインする場合にはログインの度に認証メールをクリック/タップする必要はありませんが、
    最初に「会員登録」を行う必要があります。<br><br>

    「フィードバック」「バグ報告・要望」「プライバシーポリシー」へのアクセスにもログインが必要です。<br><br>

    ログインできない場合は、<br>
    22801001@edu.cc.saga-u.ac.jp<br>
    小嶋 恒<br>
    までご連絡ください。
</p>

<script src="{% static 'login/js/mask_password.js' %}"></script>
{% endblock body %}

python/front/login/templates/htmls/password_change.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>パスワード変更</title>
{% endblock head %}

{% block body %}
<script src="{% static 'login/js/mask_password.js' %}"></script>
<script src="{% static 'login/js/mask_old_password.js' %}"></script>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    <input type="checkbox" onclick="mask_oldpassword()">Show Password(old)
    <input type="checkbox" onclick="mask_password()">Show Password(new)
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
{% endblock body %}

python/front/login/templates/htmls/password_change_done.html
{% extends "search/base.html" %}

{% block head %}
<title>パスワード変更完了</title>
{% endblock head %}

{% block body %}
<p>
    パスワードを変更しました。<br>
    <a href="{% url 'login:login' %}">ログイン</a>
</p>
{% endblock body %}

python/front/login/templates/htmls/password_reset_complete.html
{% extends "search/base.html" %}

{% block head %}
<title>パスワード再設定完了</title>
{% endblock head %}

{% block body %}
<p>
    パスワード再設定を完了しました。<br>
    <a href="{% url 'login:login' %}">ログイン</a>
</p>
{% endblock body %}

python/front/login/templates/htmls/password_reset_confirm.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>パスワードリセット</title>
{% endblock head %}

{% block body %}
<script src="{% static 'login/js/mask_password.js' %}"></script>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    <!-- An element to toggle between password visibility -->
    <input type="checkbox" onclick="mask_password()">Show Password
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
{% endblock body %}

python/front/login/templates/htmls/password_reset_done.html
{% extends "search/base.html" %}

{% block head %}
<title>メールを送信しました</title>
{% endblock head %}

{% block body %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock body %}

python/front/login/templates/htmls/password_reset_form.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>パスワードリセット</title>
<link href="{% static 'login/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button>送信</button>
</form>
{% endblock body %}

python/front/login/templates/htmls/token_error.html
{% extends "search/base.html" %}

{% block head %}
<title>トークンエラー</title>
{% endblock head %}

{% block body %}
<p>
    {{ message }}<br>
    お手数ですが、最初から手続きをお願いいたします。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'login:login' %}">ログイン画面に戻る</a>
</p>
{% endblock body %}

python/front/login/templates/htmls/user.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>ユーザー情報</title>
<link href="{% static 'login/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<br>
<h2>アカウント情報</h2>
<br><br>
<p>メールアドレス</p>
<p>{{ user.email }}</p>
<br><br>
<div><button class="button-wide">
    <a href="{% url 'login:password_change' %}" >パスワード変更</a>
</button></div>
{% endblock body %}

python/front/login/templates/htmls/user_create.html
{% extends "search/base.html" %}
{% load static %}

{% block head %}
<title>会員登録</title>
<link href="{% static 'login/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<script src="{% static 'login/js/mask_password.js' %}"></script>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    <!-- An element to toggle between password visibility -->
    <input type="checkbox" onclick="mask_password()">Show Password
    {% csrf_token %}
    <button>送信</button>
</form>

{% endblock body %}