python/front/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user/<int:pk>/', views.UserPage.as_view(), name='user'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email_login/', views.EmailLogin.as_view(), name='email_login'),
    path('email_login/complete/<token>/', views.EmailLoginComplete.as_view(), name='email_login_complete'),
]

python/front/search/urls.py
# -*- coding: utf-8 -*-
"""module description
"""

from django.urls import path

from front.search.views import index, robots_txt, privacy_policy, feedback, report, input_example

app_name='search'

urlpatterns = [
    path('', index, name='index'),
    path('privacypolicy/', privacy_policy, name='privacy_policy'),
    path('feedback/', feedback, name='feedback'),
    path('report/', report, name='report'),
    path('input_example/', input_example, name='input_example'),
    path('robots.txt', robots_txt),
]

python/front/twelS/urls.py
# -*- coding: utf-8 -*-
"""twelS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # superuserを作っていないが，一応adminのpathを推測できないものにする
    path('4KkEH5XsLQRC/', admin.site.urls),
    path('', include('search.urls')),
    path('login/', include('login.urls')), # login

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # this line is executed when DEBUG is set to True.
]

python/front/search/models.py
# -*- coding: utf-8 -*-
"""module description
"""

from django.db import models

# Create your models here.

python/front/search/views.py
# -*- coding: utf-8 -*-
"""module description
"""

import time
from urllib.parse import urlparse

from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render

from front.twelS.settings import BASE_DIR
from twels.mathpix.mathpix import mathocr
from twels.searcher.searcher import Searcher
from twels.searcher.urlparser import parse_url


@login_required
def index(request: WSGIRequest):
    """サイトに最初にアクセスしたときや検索したときに呼び出される関数．
    """
    if request.method == 'GET':
        # request.GET.get('q')をしてしまうと'%20'が' 'に
        # 変換されてしまうのでrequest.GET.get('q')などは使わない。
        full_path = request.get_full_path()
        url_params = parse_url(urlparse(full_path).query)
        page_list: list[dict] = []
        has_next = False

        # 検索時
        if url_params['q']:
            start_time = time.time()
            # TODO: 複数のキーワード検索にも対応する。
            result = Searcher.search(
                url_params['q'][0], int(url_params['start'][0]), url_params['lr']
                )
            page_list = result['search_result']
            has_next = result['has_next']
            search_time = time.time() - start_time
            print(f'search time: {search_time}秒')

        context = {
            'page_list': page_list,
            'has_next': has_next,
            'start': str(int(url_params['start'][0])+10),
            'ocr': '',
        }
        return render(request, 'search/index.html', context)

    elif request.method == 'POST':
        if request.FILES.get('uploadImage', False):
            uploadedImage: bytes = request.FILES['uploadImage'].read()
            ocr = mathocr(uploadedImage)
            if ocr is not False:
                ocr: str = ocr.replace('\\', '\\\\')
                context = {'ocr': ocr}
            else:
                context = {'ocr': ' '}
        else:
            context = {'ocr': ''}
        return render(request, 'search/index.html', context)

    else:
        print('GET,POST以外のHTTP methodでアクセスされました．HTTP method: ', request.method)
        context = {}
        return render(request, 'search/index.html', context)


@login_required
def privacy_policy(request):
    """プライバシーポリシーのページ．
    """
    return render(request, 'search/privacy_policy.html', {})


@login_required
def feedback(request):
    """問い合わせのページ"""
    context = {}
    return render(request, 'search/feedback.html', context)


@login_required
def report(request):
    """バグ報告・要望のページ"""
    context = {}
    return render(request, 'search/report.html', context)


@login_required
def input_example(request):
    """数式の入力例のページ"""
    context = {}
    return render(request, 'search/input_example.html', context)


@login_required
def robots_txt(request):
    """robots.txtを表示するための関数．
    """
    text = ''
    try:
        with open(f'{BASE_DIR}/search/static/search/robots.txt') as f:
            text = f.read()
    except Exception:
        text = 'error'
    return HttpResponse(text, content_type='text/plain')

python/front/search/templates/search/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'search/style.css' %}">
    <link rel="shortcut icon" href="{% static 'search/images/favicon.png' %}">
    {% block head %}
    <title>Title</title>
    {% endblock head %}

    {% block analytics %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FBF3VF32MV"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-FBF3VF32MV');
    </script>
    {% endblock analytics %}
</head>
<body>
    <!-- navi -->
    <nav>
        <a class="logo" href="{% url 'search:index' %}">twelS</a>
        <ul class="nav-links">
        {% if user.is_active %}
            <li>
                <a href="{% url 'login:logout' %}">ログアウト</a>
            </li>
            <li>
                <a href="{% url 'login:user' user.pk %}">ユーザーページ</a>
            </li>
        {% endif %}
        </ul>
    </nav>

    <div>
    {% block body %}
        replace me.
    {% endblock body %}
    </div>

    <footer>
        <p><a href="{% url 'search:feedback' %}">フィードバック</a>&emsp;&emsp;&emsp;&emsp;<a href="{% url 'search:report' %}">バグ報告・要望</a>&emsp;&emsp;&emsp;&emsp;<a href="{% url 'search:privacy_policy' %}">プライバシーポリシー</a></p>
    </footer>
</body>
</html>

<style>

    *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    nav {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        min-height: 8vh;
        background-color: #6168FF;
    }

    nav a {
        text-decoration: none;
    }
    
    .logo {
        color: white;
        font-size: 22px;
        padding-left: 20px;
        padding-right: 20px;
    }
    
    .nav-links {
        display: flex;
        justify-content: space-around;
    }
    
    .nav-links li {
        list-style: none;
        padding-left: 10px;
        padding-right: 10px;
    }
    
    .nav-links a {
        text-decoration: none;
        color: white;
        font-weight: bold;
    }
    
    </style>

python/front/search/templates/search/feedback.html
{% extends './base.html' %}

{% load static %}

{% block head %}
    <title>お問い合わせ</title>
{% endblock head %}

{% block body %}
<p>フィードバックのページ</p>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeMy9tcxn6o5MfI_UeacdyaedBBipn-bS_Rq3eS3wjjl8Wjag/viewform?embedded=true" width="640" height="1088" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>
{% endblock body %}

python/front/search/templates/search/index.html
{% extends './base.html' %}

{% load static %}

{% block head %}
    <!-- 公開まで検索に引っかからないようにする -->
    <meta name="robots" content="noindex">

    <title>twelS</title>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ["\\(","\\)"]] } });
    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
{% endblock head %}

{% block body %}
    <div id="main_content">
        <div id="mathCanvas"><span id="canvas"></span></div>
        
        <form id="mainForm" action="." method="GET">
            <input type="search" id="inputText" name="q" value="" oninput="renderInput()" >
            <input type="submit" value="検索">
        </form>

        <form id="imageForm" action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="uploadImage" accept="image/*" id="uploadImage" style="display: none">
        </form>

        <div class="tab-panel">
            <ul class="tab-group">
                <li class="tab tab-A is-active">演算子など</li>
                <li class="tab tab-B">ギリシャ文字</li>
                <li class="tab tab-C">行列</li>
                <li class="tab tab-D">その他</li>
                <button type="button" onclick="uploadImage()">
                    <img src="{% static 'search/images/camera-outline.png' %}" width="30" />
                </button>
            </ul>

            <div class="panel-group">
                <div class="panel tab-A is-show">
                    <button class="buttonGroup" onclick="insertExpr('+')">\(+\)</button>
                    <button class="buttonGroup" onclick="insertExpr('-')">\(-\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\times ')">\(\times\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\div ')">\(\div\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\frac{x}{y}')">\(\frac{x}{y}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('x^{n}')">\(x^{n}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('x_{n}')">\(x_{n}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\sqrt{x}')">\(\sqrt{x}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\sqrt[n]{x}')">\(\sqrt[n]{x}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\log_{y}{x}')">\(\log_{y}{x}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('=')">\(=\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\lt ')">\(\lt\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\gt ')">\(\gt\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\leqq ')">\(\leqq\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\geqq ')">\(\geqq\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\wedge ')">\(\wedge\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\vee ')">\(\vee\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\cap ')">\(\cap\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\cup ')">\(\cup\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\in ')">\(\in\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\ni ')">\(\ni\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\forall ')">\(\forall\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\exists ')">\(\exists\)</button>
                </div>
                <div class="panel tab-B">
                    <button class="buttonGroup" onclick="insertExpr('\\alpha ')">\(\alpha\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\beta ')">\(\beta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\gamma ')">\(\gamma\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\delta ')">\(\delta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\epsilon ')">\(\epsilon\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\zeta ')">\(\zeta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\eta ')">\(\eta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\theta ')">\(\theta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\iota ')">\(\iota\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\kappa ')">\(\kappa\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\lambda ')">\(\lambda\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\mu ')">\(\mu\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\nu ')">\(\nu\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\xi ')">\(\xi\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\o ')">\(o\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\pi ')">\(\pi\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\rho ')">\(\rho\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\sigma ')">\(\sigma\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\tau ')">\(\tau\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\upsilon ')">\(\upsilon\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\phi ')">\(\phi\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\chi ')">\(\chi\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\psi ')">\(\psi\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\omega ')">\(\omega\)</button>
                </div>
                <div class="panel tab-C">
                    <button class="buttonGroup" onclick="insertExpr('\\begin{matrix} a & b \\\\ c & d \\\\ \\end{matrix}')">
                        \begin{matrix} a & b \\ c & d \\ \end{matrix}
                    </button>
                    <button class="buttonGroup" onclick="insertExpr('\\begin{pmatrix} a & b \\\\ c & d \\\\ \\end{pmatrix}')">
                        \begin{pmatrix} a & b \\ c & d \\ \end{pmatrix}
                    </button>
                    <button class="buttonGroup" onclick="insertExpr('\\begin{bmatrix} a & b \\\\ c & d \\\\ \\end{bmatrix}')">
                        \begin{bmatrix} a & b \\ c & d \\ \end{bmatrix}
                    </button>
                    <button class="buttonGroup" onclick="insertExpr('\\begin{vmatrix} a & b \\\\ c & d \\\\ \\end{vmatrix}')">
                        \begin{vmatrix} a & b \\ c & d \\ \end{vmatrix}
                    </button>
                </div>
                <div class="panel tab-D">
                    <button class="buttonGroup" onclick="insertExpr('\\infty ')">\(\infty\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\partial ')">\(\partial\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\nabla ')">\(\nabla\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\Delta ')">\(\Delta\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\ln{x}')">\(\ln{x}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\int_{a}^{b} f(x) dx')">\(\int_{a}^{b} f(x) dx\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\lim_{n \\to \\infty}x_{n}')">\(\lim_{n \to \infty}x_{n}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('f\\left(x\\right)')">\(f\left(x\right)\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\left| x \\right|')">\(\left| x \right|\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\sum_{i=1}^{n}x_{i}')">\(\sum_{i=1}^{n}x_{i}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('\\prod_{i=1}^{n}x_{i}')">\(\prod_{i=1}^{n}x_{i}\)</button>
                    <button class="buttonGroup" onclick="insertExpr('a \\equiv b \\pmod n')">\(a \equiv b \pmod n\)</button>
                </div>
            </div>
        </div>

        <form id="lang" name="lang">
            <p>検索対象の言語</p><br>
            <label><input type="checkbox" name="lr" value="ja" checked><span>日本語</span></label>
            &emsp;
            <label><input type="checkbox" name="lr" value="en"><span>English</span></label>
        </form>

        <!-- HTMLは複数のスペースを1つにまとめる点に注意。 -->
        <div><p id="result"></p><br></div>

        {% for page in page_list %}
            <div class="page">
                <div class="fade"></div>
                <a href="{{ page.uri }}"><h3>{{ page.title }}</h3></a>
                <p>{{ page.snippet|safe }}</p><br>
            </div>
        {% endfor %}

        <div id="next_page"></div>
        <div id="news"></div>
    </div>

    <div id="url" style="display: none;">{% url 'search:input_example' %}</div>
    <div id="page_list" style="display: none;">{{ page_list }}</div>
    <div id="start" style="display: none;">{{ start }}</div>

    <script type="text/javascript" src="{% static 'search/js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'search/js/uploadImage.js' %}"></script>
    <script type="text/javascript">
        window.onload = onLoad;

        /** 
         * Windowを読み込んだ際に実行される関数。
         * GET parameterの反映等を行う。
         */
        function onLoad(){
            var inputText = document.getElementById('inputText');
            inputText.focus();
            
            const params = getUrlParam();

            // 入力欄にqueryを反映
            let ocr = '{{ ocr|safe }}';
            if (ocr !== '') {
                inputText.value = ocr;
            } else if (params['q'] != null) {
                inputText.value = params['q'];
                let result = document.getElementById('result');
                result.textContent = params['q'] + 'の検索結果';

                const page_list = document.getElementById('page_list').textContent;
                const start = document.getElementById('start').textContent;
                if (page_list == '[]') {
                    let news = document.getElementById('news');
                    news.innerHTML = '<p>検索結果は見つかりませんでした。</p>';
                } else if ('{{ has_next }}' == 'True') {
                    let nextPage = document.getElementById('next_page');
                    const lr = getLRString();
                    nextPage.innerHTML = `<a href="./?q=${params['q']}&start=${start}${lr}">更に表示</a>`;
                }
            } else {
                const url = document.getElementById('url');
                let paragraph = document.createElement('p');
                paragraph.innerHTML = '数式の入力はTeXの記法に対応しています。<br>数式の' 
                    + `<a href="${url.textContent}">入力例</a>`
                    + '<br><br>自然言語の検索ができるようになりました。';
                
                let news = document.getElementById('news');
                news.appendChild(paragraph);
            }
            renderInput();

            reflectLRParam(params['lr']);
        }
    </script>
{% endblock body %}

python/front/search/templates/search/input_example.html
{% extends './base.html' %}

{% load static %}

{% block head %}
    <title>数式の入力例</title>
{% endblock head %}

{% block body %}
<p>
    数式の入力例<br><br>

    (1)分数<br>
    <math xmlns="http://www.w3.org/1998/Math/MathML"  alttext="{\displaystyle {\frac {n}{d}}}">
        <semantics>
          <mrow class="MJX-TeXAtom-ORD">
            <mstyle displaystyle="true" scriptlevel="0">
              <mrow class="MJX-TeXAtom-ORD">
                <mfrac>
                  <mi>x</mi>
                  <mi>y</mi>
                </mfrac>
              </mrow>
            </mstyle>
          </mrow>
          <annotation encoding="application/x-tex">{\displaystyle {\frac {n}{d}},\quad n/d,\quad d{\backslash }n}</annotation>
        </semantics>
    </math>

    <br><br>
    \frac{x}{y}
    <br><br><br><br>

    (2)上付き文字<br>
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <semantics>
            <mrow>
                <mi>E</mi>
                <mo>=</mo>
                <mi>m</mi>
                <msup>
                    <mi>c</mi>
                    <mn>2</mn>
                </msup>
            </mrow>
            <annotation encoding="application/x-tex">E =mc^2</annotation>
        </semantics>
    </math>

    <br><br>
    E=mc^{2}
    <br><br><br><br>

    (3)行列式<br>
    <math display="block" xmlns="http://www.w3.org/1998/Math/MathML"  alttext="{\displaystyle {\begin{vmatrix}a&amp;b\\c&amp;d\end{vmatrix}}}">
        <semantics>
            <mrow class="MJX-TeXAtom-ORD">
                <mstyle displaystyle="true" scriptlevel="0">
                <mrow class="MJX-TeXAtom-ORD">
                    <mrow>
                        <mo>|</mo>
                        <mtable rowspacing="4pt" columnspacing="1em">
                            <mtr>
                            <mtd>
                                <mi>a</mi>
                            </mtd>
                            <mtd>
                                <mi>b</mi>
                            </mtd>
                            </mtr>
                            <mtr>
                            <mtd>
                                <mi>c</mi>
                            </mtd>
                            <mtd>
                                <mi>d</mi>
                            </mtd>
                            </mtr>
                        </mtable>
                        <mo>|</mo>
                    </mrow>
                </mrow>
                </mstyle>
            </mrow>
            <annotation encoding="application/x-tex">{\displaystyle {\begin{vmatrix}a&amp;b\\c&amp;d\end{vmatrix}}}</annotation>
        </semantics>
    </math>

    <br><br>
    \begin{vmatrix}<br>
    a & b \\<br>
    c & d \\<br>
    \end{vmatrix}<br>
    <br><br><br><br>

</p>


{% endblock body %}

python/front/search/templates/search/privacy_policy.html
{% extends './base.html' %}

{% load static %}

{% block head %}
    <title>プライバシーポリシー</title>
{% endblock head %}

{% block body %}
    <p>twelSではGoogle Analyticsを利用してサイトの計測を行っております．</p>
{% endblock body %}

python/front/search/templates/search/report.html
{% extends './base.html' %}

{% load static %}

{% block head %}
    <title>バグ報告・要望</title>
{% endblock head %}

{% block body %}
<h2>バグ報告・要望のページ</h2>
<br><br>

<style>
    p, li{
        text-align: left;
    }
</style>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdbejegda2RxdNXDc1ItEmL_5ysnZZ5Bvyrb47aN1OomTqiHQ/viewform?embedded=true" width="640" height="1153" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>
{% endblock body %}